### ISSUE TITLE
Unable to get the twitter emoji

### ISSUE THREAD

**Issue by meensrinivasan** [liamgilbey/ggwaffle#1]
Hello,

When I try your example 
```
library(emojifont)  
library(dplyr)

iris$Species <- as.character(iris$Species)
waffle_data <- waffle_iron(iris, aes_d(group = Species)) %>% mutate(label = fontawesome('fa-twitter'))

ggplot(waffle_data, aes(x, y, colour = group)) + 
  geom_text(aes(label=label), family='fontawesome-webfont', size=4) +
  coord_equal() + 
  scale_colour_waffle() + 
  theme_waffle()  
```
I get the following image -
![image](https://user-images.githubusercontent.com/37451822/58752622-fd783900-8477-11e9-8822-c26015b47566.png)

This is the error I get 
```
Warning messages:
1: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
2: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
3: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
4: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
```
I have downloaded fontawesome from here https://fontawesome.com/download
And have loaded the fonts using 
```
extrafont::import_font()
extrafont::loadfonts(device = "win")
```
But it still doesn't work. Thank you for your help! :)

**Comment by liamgilbey** [comment]
Hi,

I believe this actually sits with `emojifont` rather than here.
Can you please take a look at the documentation [here](https://cran.r-project.org/web/packages/emojifont/vignettes/emojifont.html#limitation) and see if that solves the problem?

**Comment by meensrinivasan** [comment]
Thank you, I think it says it is incompatible with RStudio. 

Thank you :)

**Comment by liamgilbey** [comment]
I believe if you call `windows()` before creating the plot it will work with a windows environment, even within Rstudio
