### ISSUE TITLE
Allow additional mappings to aes_d which preserve existing columns

### ISSUE THREAD

**Issue by dave-lovell** [liamgilbey/ggwaffle#10]
`aes_d` appears to only accept specific mappings. If it accepted arbitrary mappings, it could preserve columns from the original data which could subsequently be used for other plotting operations, such as `facet_wrap`.

I've not found a way to do this, so if it is possible then I think many could benefit from this being made clearer in the documentation.

I've constructed this example to explain what I mean:

``` r
## I get the favourite fruit of 100 men and 100 women:
fruits <- 
  tibble::tribble(
  ~gender,  ~fave_fruit, ~count,
  "male",    "banana",    25,
  "male",   "apple",     35,
  "male",   "pineapple", 40,
  "female", "banana",    10,
  "female", "apple",     75,
  "female", "pineapple", 15
) 

ready_to_iron <- tidyr::uncount(fruits, weights = count)

## not possible (afaik) to preserve `gender` here,
## which would allow me to subsequently facet_wrap.
ironed <- waffle_iron(ready_to_iron, aes_d(group = fave_fruit, facet_with = gender))

# Warning message:
# Columns have been supplied to aes_d but are not required:
#   facet_with 

```

My dream would be something like:

``` r
ironed <- waffle_iron(ready_to_iron, aes_d(group = fave_fruit, facet_with = gender)
## (gender variable preserved as additional row in `ironed`) ##
## Which means I can subsequently facet_wrap it  ##

ggplot2::ggplot(ironed) +
  geom_waffle(aes(x, y, fill = group)) +
  facet_wrap(~gender)
```

**Comment by liamgilbey** [comment]
Hi @dave-lovell ,

Great idea! I've just published a [new branch](https://github.com/liamgilbey/ggwaffle/tree/feature/preserve) which I think will do what you want.

I was able to run this:

```r
library(ggwaffle)

fruits <- tibble::tribble(
    ~gender,  ~fave_fruit, ~count,
    "male",    "banana",    25,
    "male",   "apple",     35,
    "male",   "pineapple", 40,
    "female", "banana",    10,
    "female", "apple",     75,
    "female", "pineapple", 15
  ) 

ready_to_iron <- tidyr::uncount(fruits, weights = count)

ironed <- waffle_iron(ready_to_iron, aes_d(group = fave_fruit, facet_with = gender))

ggplot2::ggplot(ironed) +
  geom_waffle(aes(x, y, fill = group)) +
  facet_wrap(~facet_with)
```

and get this as the result:

![image](https://user-images.githubusercontent.com/8405101/205422005-e56eee24-9e66-4cbb-83cb-52649e04adf9.png)

Test it out and let me know if that solves what you are trying to do

**Comment by jkaucic** [comment]
Hi! I have version ‘0.2.5’ installed from github and this solution does not work for me. I would also love to do facet_wrap of a waffle plot - what do I have to do? Cheers!
