### ISSUE TITLE
missing images in github pages

### ISSUE THREAD

**Issue by ashleyasmus** [liamgilbey/ggwaffle#8]
![image](https://user-images.githubusercontent.com/28746365/186965784-3ef8ba83-30de-42f7-9a25-4ebe6376c5e7.png)

**Comment by liamgilbey** [comment]
Thanks - I hadn't got my GitHub actions quite right!

![image](https://user-images.githubusercontent.com/8405101/187400487-5c770652-1b66-449b-8271-749a82259b89.png)
